runtime: python39
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

handlers:
- url: /static
  static_dir: static

# Skip unnecessary files and folders
skip_files:
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?__pycache__/.*$
  - ^(.*/)?\.DS_Store$
  - ^(.*/)?\.vscode/.*$
