runtime: python39  # Change this to your runtime if not Python
instance_class: F1  # Adjust based on your needs

handlers:
- url: /static
  static_dir: static

skip_files:
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?__pycache__/.*$
  - ^(.*/)?\.vscode/.*$
  - ^(.*/)?\.DS_Store$
  - ^(.*/)?tmp/.*$
  - ^(.*/)?.*\.log$
